# Generated by Django 4.0.4 on 2022-05-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='arma',
            new_name='id',
        ),
    ]
