# Generated by Django 4.0.4 on 2022-05-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_arma_arma_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municao',
            old_name='id',
            new_name='municao',
        ),
    ]
