# Generated by Django 4.0.4 on 2022-05-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_id_municao_municao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objeto',
            old_name='objeto_tipo_id',
            new_name='objeto_tipo',
        ),
    ]
