# Generated by Django 4.0.4 on 2022-05-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_municao_municao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='id',
            new_name='arma_id',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='id',
            new_name='municao_id',
        ),
    ]
