# Generated by Django 4.0.4 on 2022-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_id_arma_arma_id_rename_id_municao_municao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='arma_id',
            new_name='obj_id',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='municao_id',
            new_name='obj_id',
        ),
    ]
