# Generated by Django 4.0.4 on 2022-05-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_arma_id_arma_obj_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='obj_id',
            new_name='obj',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='obj_id',
            new_name='obj',
        ),
    ]
