# Generated by Django 4.0.4 on 2022-05-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_obj_id_arma_obj_rename_obj_id_municao_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='obj',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='obj',
            new_name='tipo',
        ),
    ]
