# Generated by Django 4.0.4 on 2022-05-10 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_arma_id_alter_objeto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.objeto'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
