# Generated by Django 4.0.4 on 2022-05-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_arma_objeto_alter_objeto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arma',
            name='objeto',
        ),
        migrations.AlterField(
            model_name='arma',
            name='id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.objeto'),
        ),
    ]
