# Generated by Django 4.0.4 on 2022-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_obj_arma_tipo_rename_obj_municao_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='tipo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='tipo',
            new_name='municao',
        ),
    ]
