# Generated by Django 4.0.4 on 2022-05-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_tipo_arma_id_rename_tipo_municao_municao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='id',
            new_name='id_obj',
        ),
        migrations.RenameField(
            model_name='municao',
            old_name='municao',
            new_name='id_obj',
        ),
    ]
