# Generated by Django 4.0.4 on 2022-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_id_arma_id_obj_rename_municao_municao_id_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='calibre',
            new_name='calibre_id',
        ),
    ]
