# Generated by Django 4.0.4 on 2022-05-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_arma_id_alter_municao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.calibre'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.objeto'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='calibre_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.calibre'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.objeto'),
        ),
    ]
