# Generated by Django 4.0.4 on 2022-05-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_arma_calibre_id_alter_arma_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.objeto'),
        ),
    ]
