# Generated by Django 4.0.4 on 2022-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_arma_calibre_id_alter_municao_calibre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='id',
            new_name='arma',
        ),
        migrations.RenameField(
            model_name='arma',
            old_name='calibre_id',
            new_name='calibre',
        ),
    ]
