# Generated by Django 4.0.4 on 2022-05-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_arma_calibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='arma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.objeto'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calibre'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='objeto_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto_tipo'),
        ),
    ]
