# Generated by Django 4.0.4 on 2022-05-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_arma_arma_alter_arma_calibre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municao',
            name='calibre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calibre'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.objeto'),
        ),
    ]
